name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.0.0-alpine
    steps:
    - uses: actions/checkout@v4
    - name: Install shards
      run: shards install
    - name: Test
      run: crystal spec

  different-crystal-versions:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        crystal: [1.0.0, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Download source
        uses: actions/checkout@v4

      - name: Install shards
        run: shards install

      - name: Test
        run: crystal spec

      - name: Check formatting
        run: crystal tool format; git diff --exit-code
        if: matrix.crystal == 'latest' && matrix.os == 'ubuntu-latest'
